apiVersion: v1
kind: Service
metadata:
  name: bms-service
  namespace: bms-sunil
spec:
  type: LoadBalancer
  selector:
    app: bms
  ports:
    - protocol: TCP
      port: 3000        # External port exposed to users
      targetPort: 3000  # Internal port your app listens on
